import "reflect-metadata";

// Unique symbol keys used to store metadata configuration inside classes
export const INJECT_TOKENS_KEY = Symbol("STRUXJS_INJECT_TOKENS");
export const PREC_PARAM_TYPES_KEY = Symbol("STRUXJS_PREC_PARAM_TYPES");
export const ACTION_PARAM_TYPES_KEY = Symbol("STRUXJS_ACTION_PARAM_TYPES");

/**
 * Parameter & Property Decorator: Explicitly inject dependencies by String, Symbol, or Class token
 * Can be used on constructor parameters OR class properties.
 * @param token The binding key or Class type registered in the IoC container
 */
export function Inject(token?: any): any {
    return function (target: any, propertyKey: string | symbol | undefined, parameterIndex?: number) {
        // Case 1: Used as Parameter Decorator in Constructor
        if (typeof parameterIndex === "number") {
            const actualTarget = typeof target === "function" ? target : target.constructor;
            const existingTokens: Record<number, any> = Reflect.getMetadata(INJECT_TOKENS_KEY, actualTarget) || {};
            existingTokens[parameterIndex] = token;
            Reflect.defineMetadata(INJECT_TOKENS_KEY, existingTokens, actualTarget);
        }
        // Case 2: Used as Property Decorator on Class Field
        else if (propertyKey) {
            const targetToken = token || Reflect.getMetadata("design:type", target, propertyKey);
            Object.defineProperty(target, propertyKey, {
                get() {
                    const globalContainer = (globalThis as any).__STRUXJS_CONTAINER__;
                    if (!globalContainer) {
                        throw new Error(`[StruxJS IoC Error]: Global container not initialized when resolving property '${String(propertyKey)}'.`);
                    }
                    return globalContainer.make(targetToken);
                },
                set(val: any) {
                    if (val === undefined) {
                        Object.defineProperty(this, propertyKey, {
                            get() {
                                const globalContainer = (globalThis as any).__STRUXJS_CONTAINER__;
                                if (!globalContainer) {
                                    throw new Error(`[StruxJS IoC Error]: Global container not initialized when resolving property '${String(propertyKey)}'.`);
                                }
                                return globalContainer.make(targetToken);
                            },
                            set(v: any) {
                                Object.defineProperty(this, propertyKey, { value: v, writable: true, configurable: true, enumerable: true });
                            },
                            configurable: true,
                            enumerable: true
                        });
                    } else {
                        Object.defineProperty(this, propertyKey, { value: val, writable: true, configurable: true, enumerable: true });
                    }
                },
                enumerable: true,
                configurable: true
            });
        }
    };
}

/**
 * Class Decorator: A smart scanner that freezes and preserves compile-time 
 * class dependency types, preventing TypeScript from wiping them out due to 'any' types.
 */
export function Injectable(): ClassDecorator {
    return function (target: any) {
        // Extract the raw paramtypes emitted by the TypeScript compiler
        const paramTypes = Reflect.getMetadata("design:paramtypes", target) || [];

        // Lock a precise copy into our framework's custom registry key
        Reflect.defineMetadata(PREC_PARAM_TYPES_KEY, paramTypes, target);

        return target;
    };
}

export function Action(): MethodDecorator {
    return function (target: any, propertyKey: string | symbol, descriptor: PropertyDescriptor) {
        // 1. Extract the native paramtypes generated by TypeScript for this method
        const paramTypes = Reflect.getMetadata("design:paramtypes", target, propertyKey) || [];

        // 2. Store types array directly on the method via descriptor.value
        Reflect.defineMetadata(ACTION_PARAM_TYPES_KEY, paramTypes, descriptor.value);

        return descriptor;
    };
}